"use client";

import { useCallback, useEffect, useState } from "react";

import { DashboardShell } from "@/components/DashboardShell";
import { SectionCard } from "@/components/SectionCard";
import { useAxionEmail } from "@/hooks/useAxionEmail";
import { createCalendarTestEvent, getSidebarOverview, getUpcomingEvents } from "@/lib/api";
import { formatDateTime } from "@/lib/format";
import type { CalendarEvent, SidebarOverview } from "@/lib/types";

export default function CalendarPage() {
  const { email, saveEmail } = useAxionEmail();
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [overview, setOverview] = useState<SidebarOverview | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const loadData = useCallback(async () => {
    if (!email) {
      setEvents([]);
      setOverview(null);
      return;
    }

    setLoading(true);
    setError("");
    try {
      const [eventData, overviewData] = await Promise.all([
        getUpcomingEvents(email, 15),
        getSidebarOverview(email, "i_owe"),
      ]);
      setEvents(eventData.events);
      setOverview(overviewData);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load calendar");
    } finally {
      setLoading(false);
    }
  }, [email]);

  useEffect(() => {
    void loadData();
  }, [loadData]);

  const onCreateTestEvent = async () => {
    if (!email) {
      setError("Set an email first.");
      return;
    }

    setError("");
    try {
      await createCalendarTestEvent(email);
      await loadData();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create test event");
    }
  };

  return (
    <DashboardShell
      email={email}
      onEmailSave={saveEmail}
      title="Calendar"
      subtitle="Upcoming events plus focus blocks generated by AXION"
      actions={
        <>
          <button
            type="button"
            onClick={loadData}
            className="rounded-lg border border-axion-border bg-white/5 px-3 py-2 text-sm text-axion-fg hover:bg-white/10"
          >
            Refresh
          </button>
          <button
            type="button"
            onClick={onCreateTestEvent}
            className="rounded-lg bg-axion-accent px-3 py-2 text-sm font-semibold text-slate-950 hover:brightness-105"
          >
            Create Test Event
          </button>
        </>
      }
    >
      {error ? <p className="rounded-xl border border-rose-400/40 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</p> : null}
      <div className="grid gap-4 lg:grid-cols-2">
        <SectionCard title="Upcoming Events" subtitle={loading ? "Loading..." : `${events.length} events`}>
          <ul className="space-y-2">
            {events.length === 0 && !loading ? <li className="text-sm text-axion-muted">No upcoming events.</li> : null}
            {events.map((event) => (
              <li key={event.id} className="rounded-lg border border-axion-border bg-black/20 p-3 text-sm">
                <p className="font-medium text-white">{event.summary || "Untitled Event"}</p>
                <p className="text-xs text-axion-muted">{formatDateTime(event.start)} to {formatDateTime(event.end)}</p>
                {event.html_link ? (
                  <a href={event.html_link} target="_blank" rel="noreferrer" className="mt-1 inline-block text-xs text-axion-accent">
                    Open in Google Calendar
                  </a>
                ) : null}
              </li>
            ))}
          </ul>
        </SectionCard>

        <SectionCard title="Focus Blocks" subtitle="Scheduled or suggested from latest orchestrator run">
          <p className="mb-2 text-xs text-axion-muted">Next free slot: {formatDateTime(overview?.calendar.next_free_slot)}</p>
          <ul className="space-y-2">
            {(overview?.calendar.focus_blocks ?? []).length === 0 ? (
              <li className="text-sm text-axion-muted">No focus blocks found yet.</li>
            ) : null}
            {(overview?.calendar.focus_blocks ?? []).map((block, index) => (
              <li key={`${index}-${String(block.start || "slot")}`} className="rounded-lg border border-axion-border bg-black/20 p-3 text-sm">
                <p className="font-medium text-white">{String(block.summary || "Focus Block")}</p>
                <p className="text-xs text-axion-muted">
                  {formatDateTime(String(block.start || ""))} to {formatDateTime(String(block.end || ""))}
                </p>
              </li>
            ))}
          </ul>
        </SectionCard>
      </div>
    </DashboardShell>
  );
}
